name: CI/CD to AWS EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ secrets.ECR_REPO_FRONTEND }}:${{ env.IMAGE_TAG }} ./frontend
        docker push ${{ secrets.ECR_REPO_FRONTEND }}:${{ env.IMAGE_TAG }}

    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.ECR_REPO_BACKEND }}:${{ env.IMAGE_TAG }} ./backend
        docker push ${{ secrets.ECR_REPO_BACKEND }}:${{ env.IMAGE_TAG }}

    - name: Patch Image Tags in YAMLs
      run: |
        sed -i "s|image: .*frontend.*|image: ${{ secrets.ECR_REPO_FRONTEND }}:${{ env.IMAGE_TAG }}|" k8s/frontend-deployment.yaml
        sed -i "s|image: .*backend.*|image: ${{ secrets.ECR_REPO_BACKEND }}:${{ env.IMAGE_TAG }}|" k8s/backend-deployment.yaml

    - name: Commit Updated YAMLs to GitHub
      env:
        PAT: ${{ secrets.GH_PAT }}  # Personal Access Token with repo scope
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
        git add k8s/*.yaml
        git commit -m "Update image tags to $IMAGE_TAG" || echo "No changes to commit"
        git push

    # Optional: Only needed if you're not using ArgoCD auto-sync
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}

    - name: Apply Kubernetes Manifests (optional - if ArgoCD not used)
      run: |
        kubectl apply -f ./k8s/
