name: CI/CD to AWS EKS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Frontend image
      run: |
        IMAGE_URI=${{ secrets.ECR_REPO_FRONTEND }}:latest
        docker build -t $IMAGE_URI ./frontend
        docker push $IMAGE_URI
    - name: Build and push Backend image
      run: |
        IMAGE_URI=${{ secrets.ECR_REPO_BACKEND }}:latest
        docker build -t $IMAGE_URI ./backend
        docker push $IMAGE_URI
    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.CLUSTER_NAME }}
    - name: Update frontend image in deployment
      run: |
         kubectl set image deployment/frontend frontend=$FRONTEND_REPO:$IMAGE_TAG
    - name: Update backend image in deployment
      run: |
        kubectl set image deployment/backend backend=$BACKEND_REPO:$IMAGE_TAG
    - name: Deploy to EKS
      run: |
        kubectl apply -f ./k8s/
    - name: Restart frontend deployment
      run: |
        kubectl rollout restart deployment/frontend
